let DATA;
const $=s=>document.querySelector(s);
function layout(){return{margin:{l:45,r:15,t:18,b:42},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#cbd3df",family:"Inter,system-ui,sans-serif"},xaxis:{gridcolor:"rgba(255,255,255,.05)",zerolinecolor:"rgba(255,255,255,.08)"},yaxis:{gridcolor:"rgba(255,255,255,.05)",zerolinecolor:"rgba(255,255,255,.08)"},showlegend:false}}
function drawDev(k){const v=DATA.deviance[k],l=layout();l.yaxis.title="Relative Deviance";const vals=[v.GLM,v.LightGBM,v.XGBoost];l.yaxis.range=[0,Math.max(...vals)*1.12];l.yaxis.zeroline=true;l.yaxis.zerolinecolor="rgba(255,255,255,.2)";Plotly.react("dev",[{x:["GLM","LightGBM","XGBoost"],y:[v.GLM,v.LightGBM,v.XGBoost],type:"bar",marker:{color:["#68758a","#72d5c5","#a9b3c5"]}}],l,{displayModeBar:false,responsive:true})}
function drawGini(k){const v=DATA.gini[k],l=layout();l.yaxis.title="Gini";const vals=[v.GLM,v.LightGBM,v.XGBoost];const lo=Math.min(...vals),hi=Math.max(...vals);const span=Math.max(0.05,hi-lo);l.yaxis.range=[lo-span*.18,hi+span*.18];l.yaxis.zeroline=true;l.yaxis.zerolinecolor="rgba(255,255,255,.25)";Plotly.react("gini",[{x:["GLM","LightGBM","XGBoost"],y:[v.GLM,v.LightGBM,v.XGBoost],type:"bar",marker:{color:["#68758a","#72d5c5","#a9b3c5"]}}],l,{displayModeBar:false,responsive:true})}
function bind(){document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.parentElement.parentElement.querySelector("#dev"))drawDev(b.dataset.kind);else drawGini(b.dataset.kind)})}
function bindBoard(){const order=[["GLM","glm"],["LightGBM","lgbm"],["XGBoost","xgb"]];order.forEach(([model,id])=>{document.getElementById(`freq-dev-${id}`).textContent=Number(DATA.deviance.frequency[model]).toFixed(3).replace(".",",");document.getElementById(`freq-gini-${id}`).textContent=Number(DATA.gini.frequency[model]).toFixed(4).replace(".",",")});const best=order.map(([model])=>[model,Number(DATA.gini.frequency[model])]).sort((a,b)=>b[1]-a[1])[0];document.getElementById("ch4-best-gini").textContent=best[1].toFixed(4).replace(".",",");document.getElementById("ch4-best-gini-label").textContent=`Highest frequency Gini on the test set: ${best[0]}.`; }
function progress(){const p=$("#progress");let tick=false;const u=()=>{const m=document.documentElement.scrollHeight-innerHeight;p.style.width=(m?100*scrollY/m:0)+"%";tick=false};addEventListener("scroll",()=>{if(!tick){requestAnimationFrame(u);tick=true}},{passive:true});u()}
fetch("data/chapter4_business_test.json").then(r=>{if(!r.ok)throw new Error("Chapter 4 JSON could not be loaded.");return r.json()}).then(d=>{
DATA=d;
bindBoard();
document.getElementById("ch4-glm-median").textContent=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(d.audit.glm_median);
document.getElementById("ch4-xgb-median").textContent=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",minimumFractionDigits:2}).format(d.audit.xgb_median);
drawDev("frequency");drawGini("frequency");bind();progress()
}).catch(e=>{console.error(e);document.querySelectorAll(".chart").forEach(el=>el.innerHTML='<div class="data-error">DATA ERROR · Kapitel-Daten konnten nicht geladen werden.</div>');progress()});
